"""Strict public data contracts."""

from toss_dashboard_api.contracts.authority import (
    AUTHORITY_BUNDLE_CONTRACT_VERSION,
    AUTHORITY_EVIDENCE_APPLICATION_CONTRACT_VERSION,
    AUTHORITY_EVIDENCE_CONTRACT_VERSION,
    AUTHORITY_IDENTIFIER_CLAIM_CONTRACT_VERSION,
    AUTHORITY_SOURCE_POLICY_CONTRACT_VERSION,
    ISSUER_DECISION_CONTRACT_VERSION,
    LOCAL_DATA_STEWARD_AUTHENTICATION_CONTRACT_VERSION,
)
from toss_dashboard_api.contracts.base import CONTRACT_VERSION, StrictContract
from toss_dashboard_api.contracts.provider_identity import PROVIDER_IDENTITY_CONTRACT_VERSION
from toss_dashboard_api.contracts.provider_source import PROVIDER_SOURCE_CONTRACT_VERSION

__all__ = [
    "AUTHORITY_BUNDLE_CONTRACT_VERSION",
    "AUTHORITY_EVIDENCE_APPLICATION_CONTRACT_VERSION",
    "AUTHORITY_EVIDENCE_CONTRACT_VERSION",
    "AUTHORITY_IDENTIFIER_CLAIM_CONTRACT_VERSION",
    "AUTHORITY_SOURCE_POLICY_CONTRACT_VERSION",
    "CONTRACT_VERSION",
    "ISSUER_DECISION_CONTRACT_VERSION",
    "LOCAL_DATA_STEWARD_AUTHENTICATION_CONTRACT_VERSION",
    "PROVIDER_IDENTITY_CONTRACT_VERSION",
    "PROVIDER_SOURCE_CONTRACT_VERSION",
    "StrictContract",
]
