from enum import StrEnum


class DataMode(StrEnum):
    FIXTURE = "FIXTURE"


class MissingReason(StrEnum):
    NOT_PROVIDED = "NOT_PROVIDED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    UNAVAILABLE = "UNAVAILABLE"
    UNRESOLVED = "UNRESOLVED"
    PARSE_ERROR = "PARSE_ERROR"
    WITHHELD = "WITHHELD"


class AvailabilityStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    DEGRADED = "DEGRADED"
    ERROR = "ERROR"
    UNAVAILABLE = "UNAVAILABLE"


class FreshnessStatus(StrEnum):
    FRESH = "FRESH"
    STALE = "STALE"
    EXPIRED = "EXPIRED"
    UNKNOWN = "UNKNOWN"


class FinalityStatus(StrEnum):
    PRELIMINARY = "PRELIMINARY"
    FINAL = "FINAL"
    REVISED = "REVISED"
    UNKNOWN = "UNKNOWN"


class RevisionStatus(StrEnum):
    ORIGINAL = "ORIGINAL"
    AMENDED = "AMENDED"
    SUPERSEDED = "SUPERSEDED"
    MERGED = "MERGED"


class Market(StrEnum):
    KR = "KR"
    US = "US"


class Jurisdiction(StrEnum):
    KR = "KR"
    US = "US"


class Currency(StrEnum):
    KRW = "KRW"
    USD = "USD"


class ShareClass(StrEnum):
    COMMON = "COMMON"


class MappingStatus(StrEnum):
    VERIFIED = "VERIFIED"
    UNRESOLVED = "UNRESOLVED"


class SourceSystem(StrEnum):
    FIXTURE_KR_REGULATOR = "FIXTURE_KR_REGULATOR"
    FIXTURE_US_REGULATOR = "FIXTURE_US_REGULATOR"
    FIXTURE_MARKET = "FIXTURE_MARKET"


class SourceType(StrEnum):
    FILING = "FILING"
    MARKET_DATA = "MARKET_DATA"
    FINANCIAL = "FINANCIAL"
    HOLDING = "HOLDING"


class ProviderSystem(StrEnum):
    TOSS_OPEN_API = "TOSS_OPEN_API"


class ProviderDataset(StrEnum):
    STOCK_DISCOVERY = "STOCK_DISCOVERY"
    STOCK_DETAIL = "STOCK_DETAIL"
    CURRENT_PRICE = "CURRENT_PRICE"
    DAILY_FLOW = "DAILY_FLOW"


class ProviderHttpMethod(StrEnum):
    GET = "GET"


class CollectionAttemptStatus(StrEnum):
    STARTED = "STARTED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    PARTIAL = "PARTIAL"


class ProviderAuditEventType(StrEnum):
    RAW_PERSISTED = "RAW_PERSISTED"
    SOURCE_APPENDED = "SOURCE_APPENDED"
    DUPLICATE_OBSERVED = "DUPLICATE_OBSERVED"
    VALIDATION_REJECTED = "VALIDATION_REJECTED"
    LATEST_ACCEPTED = "LATEST_ACCEPTED"


class ProviderIdentityState(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    QUARANTINED = "QUARANTINED"
    UNRESOLVED_COLLISION = "UNRESOLVED_COLLISION"


class ProviderIdentifierKind(StrEnum):
    SYMBOL = "SYMBOL"
    ISIN = "ISIN"
    LIST_DATE = "LIST_DATE"
    MARKET = "MARKET"


class ProviderIdentifierReason(StrEnum):
    INITIAL = "INITIAL"
    ENRICHMENT = "ENRICHMENT"
    CORRECTION = "CORRECTION"
    SYMBOL_CHANGE = "SYMBOL_CHANGE"


class ProviderListingMarket(StrEnum):
    KOSPI = "KOSPI"
    KOSDAQ = "KOSDAQ"
    NYSE = "NYSE"
    NASDAQ = "NASDAQ"
    AMEX = "AMEX"
    KR_ETC = "KR_ETC"
    US_ETC = "US_ETC"


class ProviderSecurityType(StrEnum):
    STOCK = "STOCK"
    FOREIGN_STOCK = "FOREIGN_STOCK"
    DEPOSITARY_RECEIPT = "DEPOSITARY_RECEIPT"
    INFRASTRUCTURE_FUND = "INFRASTRUCTURE_FUND"
    REIT = "REIT"
    ETF = "ETF"
    FOREIGN_ETF = "FOREIGN_ETF"
    ETN = "ETN"
    STOCK_WARRANTS = "STOCK_WARRANTS"


class ProviderSecurityStatus(StrEnum):
    SCHEDULED = "SCHEDULED"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    DELISTED = "DELISTED"


class ProviderSecurityMasterState(StrEnum):
    DISCOVERED = "DISCOVERED"
    DETAIL_VALID = "DETAIL_VALID"
    ELIGIBLE_FOR_MAPPING = "ELIGIBLE_FOR_MAPPING"
    MAPPED_VERIFIED = "MAPPED_VERIFIED"
    DISCOVERY_MISSING = "DISCOVERY_MISSING"
    INACTIVE_OBSERVED = "INACTIVE_OBSERVED"
    DELISTED_OBSERVED = "DELISTED_OBSERVED"
    QUARANTINED = "QUARANTINED"


class ProviderReconciliationOutcome(StrEnum):
    DISCOVERY_RECORDED = "DISCOVERY_RECORDED"
    DISCOVERY_MISSING = "DISCOVERY_MISSING"
    DETAIL_MISSING = "DETAIL_MISSING"
    DETAIL_REJECTED = "DETAIL_REJECTED"
    IDENTITY_ALLOCATED = "IDENTITY_ALLOCATED"
    IDENTITY_REUSED = "IDENTITY_REUSED"
    UNRESOLVED_COLLISION = "UNRESOLVED_COLLISION"
    UNSUPPORTED = "UNSUPPORTED"


class ProviderDetailBatchStatus(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    FAILED_EMPTY_RESPONSE = "FAILED_EMPTY_RESPONSE"


class AdjustmentStatus(StrEnum):
    RAW = "RAW"


class Participant(StrEnum):
    INDIVIDUAL = "INDIVIDUAL"
    FOREIGN = "FOREIGN"
    INSTITUTION = "INSTITUTION"


class ReportType(StrEnum):
    QUARTERLY = "QUARTERLY"


class StatementType(StrEnum):
    INCOME_STATEMENT = "INCOME_STATEMENT"


class Consolidation(StrEnum):
    CONSOLIDATED = "CONSOLIDATED"
    SEPARATE = "SEPARATE"


class ManagerType(StrEnum):
    ACTIVE_ASSET_MANAGER = "ACTIVE_ASSET_MANAGER"


class ReportingStructure(StrEnum):
    DIRECT = "DIRECT"


class HoldingChangeClass(StrEnum):
    NEW = "NEW"
    AGGRESSIVE_ADD = "AGGRESSIVE_ADD"
    ADD = "ADD"
    HOLD = "HOLD"
    TRIM = "TRIM"
    AGGRESSIVE_REDUCE = "AGGRESSIVE_REDUCE"
    EXIT = "EXIT"
    PERSISTENT_BUILD = "PERSISTENT_BUILD"
    PERSISTENT_DISTRIBUTION = "PERSISTENT_DISTRIBUTION"
    SECTOR_ROTATION_IN = "SECTOR_ROTATION_IN"
    SECTOR_ROTATION_OUT = "SECTOR_ROTATION_OUT"


class FilingFormType(StrEnum):
    QUARTERLY_REPORT = "QUARTERLY_REPORT"


class FilingChangeType(StrEnum):
    ADDED = "ADDED"
    REMOVED = "REMOVED"
    MODIFIED = "MODIFIED"
    MOVED = "MOVED"
    NUMBER_CHANGED = "NUMBER_CHANGED"
    TONE_UP = "TONE_UP"
    TONE_DOWN = "TONE_DOWN"
    UNCERTAINTY_UP = "UNCERTAINTY_UP"
    UNCERTAINTY_DOWN = "UNCERTAINTY_DOWN"
    RISK_ADDED = "RISK_ADDED"
    RISK_REMOVED = "RISK_REMOVED"


class ReviewStatus(StrEnum):
    UNREVIEWED = "UNREVIEWED"
    REVIEWED = "REVIEWED"


class SampleResult(StrEnum):
    SAMPLE_RESULT = "SAMPLE_RESULT"


class Scenario(StrEnum):
    BEAR = "BEAR"
    BASE = "BASE"
    BULL = "BULL"


class ValuationMethod(StrEnum):
    PER = "PER"


class AssumptionSource(StrEnum):
    USER_ASSUMPTION = "USER_ASSUMPTION"


class EvidenceBasis(StrEnum):
    DIRECT_SOURCE = "DIRECT_SOURCE"
    CALCULATED = "CALCULATED"
    STRUCTURAL_INFERENCE = "STRUCTURAL_INFERENCE"


class VerificationStatus(StrEnum):
    LATEST_VERIFIED = "LATEST_VERIFIED"
    UNCONFIRMED = "UNCONFIRMED"
    NOT_CHECKED = "NOT_CHECKED"


class EvidenceDirection(StrEnum):
    SUPPORTING = "SUPPORTING"
    CONTRADICTING = "CONTRADICTING"
    NEUTRAL = "NEUTRAL"
