/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/companies/{issuer_id}/data-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company Data Quality */
        get: operations["company_data_quality_api_v1_companies__issuer_id__data_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{issuer_id}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company Overview */
        get: operations["company_overview_api_v1_companies__issuer_id__overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sample/analysis-packet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analysis Packet */
        get: operations["analysis_packet_api_v1_sample_analysis_packet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/securities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Securities */
        get: operations["securities_api_v1_securities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["system_status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdjustmentStatus
         * @enum {string}
         */
        AdjustmentStatus: "RAW";
        /** AnalysisPacket */
        AnalysisPacket: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            /** Evidence Ids */
            evidence_ids: string[];
            extensions: components["schemas"]["PacketExtensions"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Input Data Ids */
            input_data_ids: string[];
            /** Issuer Id */
            issuer_id: string;
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            /** Normalized Content Hash */
            normalized_content_hash: string;
            /** Packet Id */
            packet_id: string;
            result_status: components["schemas"]["SampleResult"];
            /** Selected Security Id */
            selected_security_id: string;
            /** Source Manifest */
            source_manifest: components["schemas"]["PacketSourceManifestEntry"][];
        };
        /** AnalysisPacketResponse */
        AnalysisPacketResponse: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            data: components["schemas"]["AnalysisPacket"];
            /**
             * Data Mode
             * @constant
             */
            data_mode: "FIXTURE";
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
        };
        /**
         * AssumptionSource
         * @enum {string}
         */
        AssumptionSource: "USER_ASSUMPTION";
        /**
         * AvailabilityStatus
         * @enum {string}
         */
        AvailabilityStatus: "AVAILABLE" | "DEGRADED" | "ERROR" | "UNAVAILABLE";
        /** CompanyOverview */
        CompanyOverview: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            /** Data Quality */
            data_quality?: components["schemas"]["DataQualityStatus"][];
            /** Evidence */
            evidence?: components["schemas"]["Evidence"][];
            /** Filing Documents */
            filing_documents?: components["schemas"]["FilingDocument"][];
            /** Filing Sentence Changes */
            filing_sentence_changes?: components["schemas"]["FilingSentenceChange"][];
            /** Financial Facts */
            financial_facts?: components["schemas"]["FinancialFact"][];
            /** Institution Holding Changes */
            institution_holding_changes?: components["schemas"]["InstitutionHoldingChange"][];
            /** Institution Holdings */
            institution_holdings?: components["schemas"]["InstitutionHolding"][];
            /** Institution Managers */
            institution_managers?: components["schemas"]["InstitutionManager"][];
            issuer: components["schemas"]["Issuer"];
            /** Market Flows */
            market_flows?: components["schemas"]["DailyMarketFlow"][];
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            /** Price Bars */
            price_bars?: components["schemas"]["PriceBar"][];
            security: components["schemas"]["Security"];
            /** Selected Security Id */
            selected_security_id: string;
            /** Valuation Scenarios */
            valuation_scenarios?: components["schemas"]["ValuationScenario"][];
        };
        /** CompanyOverviewResponse */
        CompanyOverviewResponse: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            data: components["schemas"]["CompanyOverview"];
            /**
             * Data Mode
             * @constant
             */
            data_mode: "FIXTURE";
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
        };
        /**
         * Consolidation
         * @enum {string}
         */
        Consolidation: "CONSOLIDATED" | "SEPARATE";
        /**
         * Currency
         * @enum {string}
         */
        Currency: "KRW" | "USD";
        /** DailyMarketFlow */
        DailyMarketFlow: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            currency: components["schemas"]["Currency"];
            finality_status: components["schemas"]["FinalityStatus"];
            freshness_status: components["schemas"]["FreshnessStatus"];
            /** Market Flow Id */
            market_flow_id: string;
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            /** Net Quantity */
            net_quantity: string | null;
            /** Net Value */
            net_value: string | null;
            /** Normalized Content Hash */
            normalized_content_hash: string;
            participant: components["schemas"]["Participant"];
            /** Provisional */
            provisional: boolean;
            revision_status: components["schemas"]["RevisionStatus"];
            /** Security Id */
            security_id: string;
            /** Source Record Id */
            source_record_id: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
        };
        /** DataQualityResponse */
        DataQualityResponse: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            /** Count */
            count: number;
            /** Data */
            data: components["schemas"]["DataQualityStatus"][];
            /**
             * Data Mode
             * @constant
             */
            data_mode: "FIXTURE";
            /** Issuer Id */
            issuer_id: string;
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
        };
        /** DataQualityStatus */
        DataQualityStatus: {
            availability_status: components["schemas"]["AvailabilityStatus"];
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            /** Dataset */
            dataset: string;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            finality_status: components["schemas"]["FinalityStatus"];
            /**
             * Freshness Evaluated At
             * Format: date-time
             */
            freshness_evaluated_at: string;
            freshness_status: components["schemas"]["FreshnessStatus"];
            /** Issuer Id */
            issuer_id: string;
            /**
             * Last Attempt At
             * Format: date-time
             */
            last_attempt_at: string;
            /** Last Observed At */
            last_observed_at: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            /** Normalized Content Hash */
            normalized_content_hash: string;
            /** Quality Flags */
            quality_flags: string[];
            /** Quality Status Id */
            quality_status_id: string;
            /** Records Received */
            records_received: number;
            /** Records Rejected */
            records_rejected: number;
            revision_status: components["schemas"]["RevisionStatus"];
            /** Source Locator */
            source_locator: string;
            /** Source Record Id */
            source_record_id: string | null;
            source_system: components["schemas"]["SourceSystem"];
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            error: components["schemas"]["ErrorBody"];
            /** Request Id */
            request_id: string;
        };
        /** Evidence */
        Evidence: {
            /** Claim */
            claim: string;
            /** Confidence */
            confidence: string;
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            direction: components["schemas"]["EvidenceDirection"];
            evidence_basis: components["schemas"]["EvidenceBasis"];
            /** Evidence Id */
            evidence_id: string;
            /** Issuer Id */
            issuer_id: string;
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            /** Normalized Content Hash */
            normalized_content_hash: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Source Excerpt */
            source_excerpt: string | null;
            /** Source Record Id */
            source_record_id: string | null;
            verification_status: components["schemas"]["VerificationStatus"];
        };
        /**
         * EvidenceBasis
         * @enum {string}
         */
        EvidenceBasis: "DIRECT_SOURCE" | "CALCULATED" | "STRUCTURAL_INFERENCE";
        /**
         * EvidenceDirection
         * @enum {string}
         */
        EvidenceDirection: "SUPPORTING" | "CONTRADICTING" | "NEUTRAL";
        /**
         * FilingChangeType
         * @enum {string}
         */
        FilingChangeType: "ADDED" | "REMOVED" | "MODIFIED" | "MOVED" | "NUMBER_CHANGED" | "TONE_UP" | "TONE_DOWN" | "UNCERTAINTY_UP" | "UNCERTAINTY_DOWN" | "RISK_ADDED" | "RISK_REMOVED";
        /** FilingDocument */
        FilingDocument: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            /**
             * Filed At
             * Format: date-time
             */
            filed_at: string;
            /** Filing Id */
            filing_id: string;
            form_type: components["schemas"]["FilingFormType"];
            /** Issuer Id */
            issuer_id: string;
            jurisdiction: components["schemas"]["Jurisdiction"];
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            /** Normalized Content Hash */
            normalized_content_hash: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            revision_status: components["schemas"]["RevisionStatus"];
            /** Source Record Id */
            source_record_id: string;
            /** Supersedes Filing Id */
            supersedes_filing_id: string | null;
        };
        /**
         * FilingFormType
         * @enum {string}
         */
        FilingFormType: "QUARTERLY_REPORT";
        /** FilingSentenceChange */
        FilingSentenceChange: {
            /** Change Id */
            change_id: string;
            /** Change Types */
            change_types: components["schemas"]["FilingChangeType"][];
            /** Confidence */
            confidence: string;
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            /** Current Filing Id */
            current_filing_id: string;
            /** Current Sentence */
            current_sentence: string;
            /** Human Review Required */
            human_review_required: boolean;
            /** Issuer Id */
            issuer_id: string;
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            /** Normalized Content Hash */
            normalized_content_hash: string;
            /** Previous Filing Id */
            previous_filing_id: string;
            /** Previous Sentence */
            previous_sentence: string;
            primary_change_type: components["schemas"]["FilingChangeType"];
            result_status: components["schemas"]["SampleResult"];
            review_status: components["schemas"]["ReviewStatus"];
            /** Rule Hits */
            rule_hits: string[];
            /** Section Key */
            section_key: string;
            /** Semantic Similarity */
            semantic_similarity: string;
        };
        /**
         * FinalityStatus
         * @enum {string}
         */
        FinalityStatus: "PRELIMINARY" | "FINAL" | "REVISED" | "UNKNOWN";
        /** FinancialFact */
        FinancialFact: {
            /** Account Code */
            account_code: string;
            /** Account Name Original */
            account_name_original: string;
            consolidation: components["schemas"]["Consolidation"];
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            currency: components["schemas"]["Currency"];
            finality_status: components["schemas"]["FinalityStatus"];
            /** Financial Fact Id */
            financial_fact_id: string;
            /** Fiscal Period */
            fiscal_period: string;
            /** Issuer Id */
            issuer_id: string;
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            /** Normalized Content Hash */
            normalized_content_hash: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            report_type: components["schemas"]["ReportType"];
            revision_status: components["schemas"]["RevisionStatus"];
            /** Source Record Id */
            source_record_id: string;
            statement: components["schemas"]["StatementType"];
            /** Unit Scale */
            unit_scale: string;
            /** Value */
            value: string | null;
        };
        /**
         * FreshnessStatus
         * @enum {string}
         */
        FreshnessStatus: "FRESH" | "STALE" | "EXPIRED" | "UNKNOWN";
        /** HealthResponse */
        HealthResponse: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            /**
             * Data Mode
             * @constant
             */
            data_mode: "FIXTURE";
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            /** Service */
            service: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * HoldingChangeClass
         * @enum {string}
         */
        HoldingChangeClass: "NEW" | "AGGRESSIVE_ADD" | "ADD" | "HOLD" | "TRIM" | "AGGRESSIVE_REDUCE" | "EXIT" | "PERSISTENT_BUILD" | "PERSISTENT_DISTRIBUTION" | "SECTOR_ROTATION_IN" | "SECTOR_ROTATION_OUT";
        /** InstitutionHolding */
        InstitutionHolding: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            /** Cusip Original */
            cusip_original: string;
            /** Filing Id */
            filing_id: string;
            /** Holding Id */
            holding_id: string;
            /** Issuer Name Original */
            issuer_name_original: string;
            /** Manager Id */
            manager_id: string;
            mapping_status: components["schemas"]["MappingStatus"];
            /** Market Value Reported */
            market_value_reported: string;
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            /** Normalized Content Hash */
            normalized_content_hash: string;
            /** Portfolio Weight */
            portfolio_weight: string;
            /** Put Call */
            put_call: string | null;
            /**
             * Report Period
             * Format: date
             */
            report_period: string;
            reported_currency: components["schemas"]["Currency"];
            /** Reported Unit Scale */
            reported_unit_scale: string;
            /** Security Id */
            security_id: string;
            /** Shares */
            shares: string;
            /** Source Record Id */
            source_record_id: string;
            /** Title Of Class */
            title_of_class: string;
        };
        /** InstitutionHoldingChange */
        InstitutionHoldingChange: {
            change_class: components["schemas"]["HoldingChangeClass"];
            /** Confidence */
            confidence: string;
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            /**
             * Current Period
             * Format: date
             */
            current_period: string;
            /** Current Shares */
            current_shares: string;
            /** Estimated Trade Effect */
            estimated_trade_effect: string | null;
            /** Holding Change Id */
            holding_change_id: string;
            /** Limitations */
            limitations: string[];
            /** Manager Id */
            manager_id: string;
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            /** Normalized Content Hash */
            normalized_content_hash: string;
            /**
             * Previous Period
             * Format: date
             */
            previous_period: string;
            /** Previous Shares */
            previous_shares: string;
            /** Rank Delta */
            rank_delta: number;
            result_status: components["schemas"]["SampleResult"];
            /** Security Id */
            security_id: string;
            /** Shares Delta */
            shares_delta: string;
            /** Shares Delta Pct */
            shares_delta_pct: string | null;
            /** Weight Delta */
            weight_delta: string;
        };
        /** InstitutionManager */
        InstitutionManager: {
            /** Active Status */
            active_status: boolean;
            /** Cik */
            cik: string;
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            /** Display Name */
            display_name: string;
            /** Legal Name */
            legal_name: string;
            /** Manager Id */
            manager_id: string;
            manager_type: components["schemas"]["ManagerType"];
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            /** Normalized Content Hash */
            normalized_content_hash: string;
            /** Parent Manager Id */
            parent_manager_id: string | null;
            /** Reporting Manager Id */
            reporting_manager_id: string;
            reporting_structure: components["schemas"]["ReportingStructure"];
            /** Signal Weight */
            signal_weight: string;
        };
        /** Issuer */
        Issuer: {
            /** Cik */
            cik: string | null;
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            /** Corp Code */
            corp_code: string | null;
            /** Display Name */
            display_name: string;
            /** Issuer Id */
            issuer_id: string;
            jurisdiction: components["schemas"]["Jurisdiction"];
            /** Legal Name */
            legal_name: string;
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            /** Normalized Content Hash */
            normalized_content_hash: string;
        };
        /**
         * Jurisdiction
         * @enum {string}
         */
        Jurisdiction: "KR" | "US";
        /**
         * ManagerType
         * @enum {string}
         */
        ManagerType: "ACTIVE_ASSET_MANAGER";
        /**
         * MappingStatus
         * @enum {string}
         */
        MappingStatus: "VERIFIED" | "UNRESOLVED";
        /**
         * Market
         * @enum {string}
         */
        Market: "KR" | "US";
        /**
         * MissingReason
         * @enum {string}
         */
        MissingReason: "NOT_PROVIDED" | "NOT_APPLICABLE" | "UNAVAILABLE" | "UNRESOLVED" | "PARSE_ERROR" | "WITHHELD";
        /** PacketExtensions */
        PacketExtensions: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            /** Extension Version */
            extension_version: string;
            /** Hypotheses */
            hypotheses?: {
                [key: string]: string;
            }[];
            /** Invalidation Conditions */
            invalidation_conditions?: {
                [key: string]: string;
            }[];
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            /** Scenario Probability Changes */
            scenario_probability_changes?: {
                [key: string]: string;
            }[];
        };
        /** PacketSourceManifestEntry */
        PacketSourceManifestEntry: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            /** Raw Content Hash */
            raw_content_hash: string;
            /** Source Record Id */
            source_record_id: string;
        };
        /**
         * Participant
         * @enum {string}
         */
        Participant: "INDIVIDUAL" | "FOREIGN" | "INSTITUTION";
        /** PriceBar */
        PriceBar: {
            adjustment_status: components["schemas"]["AdjustmentStatus"];
            /**
             * Bar Start
             * Format: date-time
             */
            bar_start: string;
            /** Close */
            close: string;
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            currency: components["schemas"]["Currency"];
            /**
             * Exchange Trade Date
             * Format: date
             */
            exchange_trade_date: string;
            finality_status: components["schemas"]["FinalityStatus"];
            freshness_status: components["schemas"]["FreshnessStatus"];
            /** High */
            high: string;
            /** Interval */
            interval: string;
            /** Low */
            low: string;
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            /** Normalized Content Hash */
            normalized_content_hash: string;
            /** Open */
            open: string;
            /** Price Bar Id */
            price_bar_id: string;
            revision_status: components["schemas"]["RevisionStatus"];
            /** Security Id */
            security_id: string;
            /** Source Record Id */
            source_record_id: string;
            /** Volume */
            volume: string;
        };
        /**
         * ReportingStructure
         * @enum {string}
         */
        ReportingStructure: "DIRECT";
        /**
         * ReportType
         * @enum {string}
         */
        ReportType: "QUARTERLY";
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "UNREVIEWED" | "REVIEWED";
        /**
         * RevisionStatus
         * @enum {string}
         */
        RevisionStatus: "ORIGINAL" | "AMENDED" | "SUPERSEDED" | "MERGED";
        /** SafetyStatus */
        SafetyStatus: {
            /** Allow Account Endpoints */
            allow_account_endpoints: boolean;
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            /** Dry Run */
            dry_run: boolean;
            /** Local Only */
            local_only: boolean;
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            /** Openai Api Enabled */
            openai_api_enabled: boolean;
            /** Trading Enabled */
            trading_enabled: boolean;
        };
        /**
         * SampleResult
         * @enum {string}
         */
        SampleResult: "SAMPLE_RESULT";
        /**
         * Scenario
         * @enum {string}
         */
        Scenario: "BEAR" | "BASE" | "BULL";
        /** SecuritiesResponse */
        SecuritiesResponse: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            /** Count */
            count: number;
            /** Data */
            data: components["schemas"]["Security"][];
            /**
             * Data Mode
             * @constant
             */
            data_mode: "FIXTURE";
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
        };
        /** Security */
        Security: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            currency: components["schemas"]["Currency"];
            /** Cusip */
            cusip: string | null;
            /** Exchange */
            exchange: string;
            /** Figi */
            figi: string | null;
            /** Isin */
            isin: string | null;
            /** Issuer Id */
            issuer_id: string;
            mapping_status: components["schemas"]["MappingStatus"];
            market: components["schemas"]["Market"];
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            /** Normalized Content Hash */
            normalized_content_hash: string;
            /** Security Id */
            security_id: string;
            share_class: components["schemas"]["ShareClass"];
            /** Ticker */
            ticker: string;
            /** Valid From */
            valid_from: string | null;
            /** Valid To */
            valid_to: string | null;
        };
        /**
         * ShareClass
         * @enum {string}
         */
        ShareClass: "COMMON";
        /**
         * SourceSystem
         * @enum {string}
         */
        SourceSystem: "FIXTURE_KR_REGULATOR" | "FIXTURE_US_REGULATOR" | "FIXTURE_MARKET";
        /**
         * StatementType
         * @enum {string}
         */
        StatementType: "INCOME_STATEMENT";
        /** SystemStatusResponse */
        SystemStatusResponse: {
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            /**
             * Data Mode
             * @constant
             */
            data_mode: "FIXTURE";
            /** Database Revision */
            database_revision: string;
            /** Fixture Version */
            fixture_version: string;
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            safety: components["schemas"]["SafetyStatus"];
            /** Service */
            service: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * ValuationMethod
         * @enum {string}
         */
        ValuationMethod: "PER";
        /** ValuationScenario */
        ValuationScenario: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            assumption_source: components["schemas"]["AssumptionSource"];
            /**
             * Contract Version
             * @constant
             */
            contract_version: "0.1.0";
            currency: components["schemas"]["Currency"];
            /** Forecast Eps */
            forecast_eps: string;
            /** Formula Version */
            formula_version: string;
            /** Implied Price */
            implied_price: string;
            /** Input Data Ids */
            input_data_ids: string[];
            /** Issuer Id */
            issuer_id: string;
            method: components["schemas"]["ValuationMethod"];
            /** Missing Reasons */
            missing_reasons?: {
                [key: string]: components["schemas"]["MissingReason"];
            };
            /** Normalized Content Hash */
            normalized_content_hash: string;
            /** Probability */
            probability: string;
            result_status: components["schemas"]["SampleResult"];
            scenario: components["schemas"]["Scenario"];
            /** Target Multiple */
            target_multiple: string;
            /** Unit Scale */
            unit_scale: string;
            /** Valuation Run Id */
            valuation_run_id: string;
            /** Valuation Scenario Id */
            valuation_scenario_id: string;
        };
        /**
         * VerificationStatus
         * @enum {string}
         */
        VerificationStatus: "LATEST_VERIFIED" | "UNCONFIRMED" | "NOT_CHECKED";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    company_data_quality_api_v1_companies__issuer_id__data_quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issuer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQualityResponse"];
                };
            };
            /** @description Invalid host or request boundary */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Requested API resource or route was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description HTTP method is not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unhandled internal failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Required fixture data is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    company_overview_api_v1_companies__issuer_id__overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issuer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOverviewResponse"];
                };
            };
            /** @description Invalid host or request boundary */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Requested API resource or route was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description HTTP method is not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unhandled internal failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Required fixture data is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    analysis_packet_api_v1_sample_analysis_packet_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisPacketResponse"];
                };
            };
            /** @description Invalid host or request boundary */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Requested API resource or route was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description HTTP method is not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unhandled internal failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Required fixture data is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    securities_api_v1_securities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecuritiesResponse"];
                };
            };
            /** @description Invalid host or request boundary */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Requested API resource or route was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description HTTP method is not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unhandled internal failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Required fixture data is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    system_status_api_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
            /** @description Invalid host or request boundary */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Requested API resource or route was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description HTTP method is not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unhandled internal failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Required fixture data is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Invalid host or request boundary */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Requested API resource or route was not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description HTTP method is not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unhandled internal failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Required fixture data is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
