import type {
  CompanyOverview,
  DataQualityStatus,
  Security,
} from "@/types/api.contract";

const HASH = `sha256:${"0".repeat(64)}`;

export function createSecurity(): Security {
  return {
    contract_version: "0.1.0",
    normalized_content_hash: HASH,
    missing_reasons: {
      cusip: "NOT_APPLICABLE",
      isin: "NOT_PROVIDED",
      figi: "NOT_PROVIDED",
      valid_from: "NOT_PROVIDED",
      valid_to: "NOT_PROVIDED",
    },
    security_id: "sec_kr_fixture_001",
    issuer_id: "issuer_kr_fixture_001",
    market: "KR",
    exchange: "SYNTH-KR",
    ticker: "TSTK1",
    share_class: "COMMON",
    currency: "KRW",
    cusip: null,
    isin: null,
    figi: null,
    mapping_status: "VERIFIED",
    valid_from: null,
    valid_to: null,
  };
}

export function createDataQualityStatus(
  overrides: Partial<DataQualityStatus> = {},
): DataQualityStatus {
  return {
    contract_version: "0.1.0",
    normalized_content_hash: HASH,
    missing_reasons: {
      error_code: "NOT_APPLICABLE",
      error_message: "NOT_APPLICABLE",
    },
    quality_status_id: "quality_kr_fixture_market",
    issuer_id: "issuer_kr_fixture_001",
    source_system: "FIXTURE_MARKET",
    dataset: "SYNTHETIC_DAILY_PRICE",
    availability_status: "AVAILABLE",
    freshness_status: "FRESH",
    finality_status: "FINAL",
    revision_status: "ORIGINAL",
    last_attempt_at: "2026-08-16T00:10:00Z",
    last_success_at: "2026-08-16T00:10:00Z",
    last_observed_at: "2026-08-15T15:00:00Z",
    freshness_evaluated_at: "2026-08-16T01:00:00Z",
    error_code: null,
    error_message: null,
    records_received: 2,
    records_rejected: 0,
    quality_flags: [],
    source_record_id: "source_fixture_market_001",
    source_locator: "fixture://market/price",
    ...overrides,
  };
}

export function createCompanyOverview(): CompanyOverview {
  const security = createSecurity();
  return {
    contract_version: "0.1.0",
    missing_reasons: {},
    issuer: {
      contract_version: "0.1.0",
      normalized_content_hash: HASH,
      missing_reasons: { cik: "NOT_APPLICABLE" },
      issuer_id: security.issuer_id,
      legal_name: "Synthetic Grid Systems Co., Ltd.",
      display_name: "합성그리드시스템",
      jurisdiction: "KR",
      corp_code: "SYNTH0001",
      cik: null,
    },
    selected_security_id: security.security_id,
    security,
    price_bars: [
      {
        contract_version: "0.1.0",
        normalized_content_hash: HASH,
        missing_reasons: {},
        price_bar_id: "price_kr_fixture_001",
        security_id: security.security_id,
        interval: "1d",
        bar_start: "2026-08-15T06:30:00Z",
        exchange_trade_date: "2026-08-15",
        open: "999999999999999999999998.000100",
        high: "1000000000000000000000001.000100",
        low: "999999999999999999999997.000100",
        close: "999999999999999999999999.000100",
        volume: "1200000",
        currency: "KRW",
        adjustment_status: "RAW",
        source_record_id: "source_fixture_market_001",
        freshness_status: "FRESH",
        finality_status: "FINAL",
        revision_status: "ORIGINAL",
      },
    ],
    market_flows: [
      {
        contract_version: "0.1.0",
        normalized_content_hash: HASH,
        missing_reasons: { net_value: "UNAVAILABLE" },
        market_flow_id: "flow_kr_fixture_foreign",
        security_id: security.security_id,
        trade_date: "2026-08-15",
        participant: "FOREIGN",
        net_quantity: "120000",
        net_value: null,
        currency: "KRW",
        provisional: true,
        source_record_id: "source_fixture_market_001",
        freshness_status: "FRESH",
        finality_status: "PRELIMINARY",
        revision_status: "ORIGINAL",
      },
    ],
    financial_facts: [
      {
        contract_version: "0.1.0",
        normalized_content_hash: HASH,
        missing_reasons: {},
        financial_fact_id: "fact_kr_fixture_revenue",
        issuer_id: security.issuer_id,
        report_type: "QUARTERLY",
        fiscal_period: "2026Q2",
        statement: "INCOME_STATEMENT",
        account_code: "Revenue",
        account_name_original: "합성 매출액",
        value: "123456789012345678901234",
        currency: "KRW",
        unit_scale: "1",
        consolidation: "CONSOLIDATED",
        period_start: "2026-04-01",
        period_end: "2026-06-30",
        source_record_id: "source_fixture_financial_001",
        finality_status: "REVISED",
        revision_status: "AMENDED",
      },
    ],
    institution_managers: [
      {
        contract_version: "0.1.0",
        normalized_content_hash: HASH,
        missing_reasons: { parent_manager_id: "NOT_APPLICABLE" },
        manager_id: "manager_fixture_001",
        display_name: "Synthetic Capital",
        legal_name: "Synthetic Capital Fixture LLC",
        cik: "0000000001",
        manager_type: "ACTIVE_ASSET_MANAGER",
        parent_manager_id: null,
        reporting_manager_id: "manager_fixture_001",
        reporting_structure: "DIRECT",
        signal_weight: "0.70",
        active_status: true,
      },
    ],
    institution_holdings: [],
    institution_holding_changes: [
      {
        contract_version: "0.1.0",
        normalized_content_hash: HASH,
        missing_reasons: { estimated_trade_effect: "UNAVAILABLE" },
        holding_change_id: "holding_change_fixture_001",
        manager_id: "manager_fixture_001",
        security_id: security.security_id,
        previous_period: "2026-03-31",
        current_period: "2026-06-30",
        previous_shares: "800000",
        current_shares: "1000000",
        shares_delta: "200000",
        shares_delta_pct: "0.25",
        weight_delta: "0.004",
        rank_delta: -12,
        change_class: "ADD",
        estimated_trade_effect: null,
        confidence: "0.90",
        limitations: ["ACTUAL_TRADE_DATE_UNKNOWN"],
        result_status: "SAMPLE_RESULT",
      },
    ],
    filing_documents: [],
    filing_sentence_changes: [
      {
        contract_version: "0.1.0",
        normalized_content_hash: HASH,
        missing_reasons: {},
        change_id: "filing_change_fixture_001",
        issuer_id: security.issuer_id,
        previous_filing_id: "filing_fixture_original",
        current_filing_id: "filing_fixture_amended",
        section_key: "BUSINESS_OVERVIEW",
        primary_change_type: "NUMBER_CHANGED",
        change_types: ["NUMBER_CHANGED", "TONE_DOWN"],
        previous_sentence: "<img src=x onerror=alert(1)>",
        current_sentence: "합성 목표 수치를 낮추고 불확실성을 명시했습니다.",
        semantic_similarity: "0.84",
        confidence: "0.91",
        rule_hits: ["NUMBER_DELTA", "CERTAINTY_REDUCED"],
        review_status: "UNREVIEWED",
        human_review_required: true,
        result_status: "SAMPLE_RESULT",
      },
    ],
    valuation_scenarios: [
      {
        contract_version: "0.1.0",
        normalized_content_hash: HASH,
        missing_reasons: {},
        valuation_scenario_id: "valuation_fixture_base",
        valuation_run_id: "valuation_run_fixture_001",
        issuer_id: security.issuer_id,
        scenario: "BASE",
        as_of: "2026-08-16",
        method: "PER",
        forecast_eps: "12000",
        target_multiple: "17",
        implied_price: "204000",
        currency: "KRW",
        unit_scale: "1",
        probability: "0.55",
        assumption_source: "USER_ASSUMPTION",
        formula_version: "per_fixture_v1",
        input_data_ids: ["fact_kr_fixture_revenue"],
        result_status: "SAMPLE_RESULT",
      },
    ],
    evidence: [
      {
        contract_version: "0.1.0",
        normalized_content_hash: HASH,
        missing_reasons: {},
        evidence_id: "evidence_fixture_001",
        issuer_id: security.issuer_id,
        evidence_basis: "DIRECT_SOURCE",
        verification_status: "LATEST_VERIFIED",
        direction: "SUPPORTING",
        claim: "합성 원문에서 fixture 수주잔고 증가를 명시했습니다.",
        source_record_id: "source_fixture_filing_001",
        source_excerpt: "합성 fixture 원문 발췌",
        observed_at: "2026-06-30T00:00:00Z",
        confidence: "1.00",
      },
    ],
    data_quality: [createDataQualityStatus()],
  };
}
